name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0 
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  flex_color_picker: ^3.8.0
  uuid: ^4.5.3
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

fonts:
  - family: Cera Pro
    fonts:
      - assets: assets/fonts/Cera-Pro-Medium.otf
      - assets: assets/fonts/Cera-Pro-Bold.otf